double arr[50][2];
void open(double firstdeposit);
void balance(int account_number);
void deposit(int account_number,double amount);
void withdrawal (int account_number,double amount);
void close(int account_number);
void interest (int interest);
void print();
void endp();
void transaction();